spring:
  data:
    mongodb:
      database: QuotesDB
      collection: quotes
      host: localhost
      port: 27017
  mandatory-file-encoding: UTF-8
server:
  port: 8080
remote-host: http://192.168.62.221:8080
kafka:
  local-topic-name: quote-local
  replica-topic-name: quote-replica

  local-host: localhost
  local-port: 9092
  remote-host: 192.168.62.221
  remote-port: 9092

  main-partition-local-topic: 0
  reserve-partition-local-topic: 1
  producer-path: kafka-conf/innerProducer.properties
  inner-local-topic-consumer-path: kafka-conf/localTopicConsumer.properties
  outer-replica-topic-consumer-path: kafka-conf/outerReplicaConsumer.properties



