spring:
  data:
    mongodb:
      database: QuotesDB
      collection: quotes
      host: localhost
      port: 27017
  mandatory-file-encoding: UTF-8
server:
  port: 8080
  remote-host: http://192.168.62.72:8080
kafka:
  local-topic-name: quote-local
  replica-topic-name: quote-replica
  reserve-topic-name: quote-reserve

  local-host: 192.168.62.221
  local-port: 9092
  remote-host: 192.168.62.72
  remote-port: 9092



